### ISSUE TITLE
Can't run Automator workflow? get an error message

### ISSUE THREAD

**Issue by umattyw** [douglas-watson/podcasts_export#6]
Hi there,

when i try to run the workflow from Podcasts/Services i get the following error:

The action “Run Shell Script” encountered an error: “0:77: execution error: Traceback (most recent call last):
File "/Library/Developer/CommandLineTools/usr/bin/pip3", line 6, in <module>
from pip._internal import main
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>
from pip._internal.cli.autocompletion import autocomplete
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
from pip._internal.cli.main_parser import create_main_parser
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
from pip._internal.commands import (
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
from pip._internal.commands.completion import CompletionCommand
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
from pip._internal.cli.base_command import Command
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/__init__.py) (1)
Traceback (most recent call last):
File "<stdin>", line 84, in <module>
ModuleNotFoundError: No module named 'mutagen'”

any ideas?

thanks

**Comment by douglas-watson** [comment]
Hi @umattyw,

Many people have encountered similar errors, so I'm trying a different approach: packaging and distributing an actual app. Normally all libraries are included in the app bundle, which should avoid these errors. You can try it here: https://github.com/douglas-watson/podcasts_export_app.

**Comment by umattyw** [comment]
Thanks so much for the app, its working perfectly :)
